parameters:
    #Deprecated parameters
    env(ELASTICSEARCH_CLUSTER): '["http://localhost:9200"]'

    #Parameters
    env(EMS_HASH_ALGO): 'sha1'
    env(EMS_ELASTICSEARCH_HOSTS): '%env(ELASTICSEARCH_CLUSTER)%'

ems_common:
    hash_algo: '%env(string:EMS_HASH_ALGO)%'
    elasticsearch_hosts: '%env(json:EMS_ELASTICSEARCH_HOSTS)%'