sudo: false
language: php
php:
- '7.2'
install:
- echo "Stage [Install] ..."
- travis_retry composer install --no-interaction --no-suggest
script:
- echo "Stage [Test] ..."
- echo "Running PHP Unit Here ..."
branches:
  only:
  - "/^v\\d+(\\.\\d+)+$/"
  - master
deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR"
  skip_cleanup: true
  prerelease: false
  on:
    tags: true
env:
  global:
    secure: G/pXFWcctUsXGdS7jeKFa8jsjbkzlFQQdEfyhu4sEg0CDIogSWrW0q/X55pHYQ3Y7XLFNMZ3V4RQdGsnMgRvrvSzIg9q4lDSQk0jQpEMJDxdb+mPg7R/MifkylHw4n4gdumqiSGL/BfAEcL4GVjcRBjgxrEkz1GUVq2/AyCsr3di336fohpfKFi1WYK8m4X8tU+o63T4u9Yra+VW+TOWgSB3TA11sWRCp7VIIJussmNJYRc6v6N5Ekaojm27Ye3JXVTUj3VIGdzMFQwsZpXWkfefo0Rd0nf/5Kw+E6f0Hgh69qOH6Y1xYTaudPnlty3/hFPuikbInIwCtMFEvGZTGdiyLt083Z3jvo+esNbW42C0QRwzcecFhSn+bHc2i2H5R1dKTkR+IaVkgvkFqbl8eqlD/vq8rmXsPKfsOSVpMdRzI4/dIxopAxBNEF53sii33YqNq6iJexVEja/YXlScND+I7m5V9PXIUYM1ZOi6RAUBa3xiMjgxdMvgAkQG4nMOqvK8HGftVzKQ9L1y5EuB6fsNwLdOWvfzzCdo/eUpMyYcIDBGFrGDXXHPT2rN/fTXDHGOBhR3AcDs2if2ZPWL5sRDDrEDTmXJT1+eH0ktWIiisl73jNFrQVUoJS7FeUHUNNVs7WWN1k/aOusSGz3DQw+k4NgXykVSORR5HpqmMZQ=
