sudo: false

language: php

php:
  - '7.2'

install:
  - echo "Stage [Install] ..."
  - travis_retry composer install --no-interaction --no-suggest

script:
  - echo "Stage [Test] ..."
  - echo "Running PHP Unit Here ..."

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"
    - master

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR
  skip_cleanup: true
  prerelease: false
  on:
    tags: true

env:
  global:
    secure: KfDDxy/iGNtpttZLMisNwZ0RYuD5ds0MuPPCtM5auCPniSUwVdALbJMrqi66E2kkSvWobEfJmIZ8kHS+BQfRjkNCsH+KiFS5c1lq7IJv6SgMTuzhy9gmSsCGJIWnVKp9gRMf59Q03AOXTJv28OtLauz8KX3OjD+bf5P+kHmHyubFRlUzHUc2YTNaO6iU8DMVspaEsPKOjmeBDjqHWG5TJyurX0aXpRlpAw79ttrmRi8vmTJCzBoy5yFO+cPaOQGI/5LPQQ9h+IuF7FLShl51lBgOspr1+o//lQaVaqiqPCikXOcC3kF/faz1hbrX6LidZu+A3d+Z9S0hzrK6Tx6TIdpiXUf6ZZLMP+5ie13QBx964DTixjQU1UfUg8qGOmoCqEKDX0RJDQMMPrI843CBVvAilYkM1g67Einl3GNxUQj7bVWzF+/qvqec734Med2Yz4iXTkn9jJXPa8ANvQlxNp7Mwhr0tOLaPiof2CyCGe7ObjIC9Fcuj9R+YYlAAfv2cz9tWVIwu8AnDiRjr3nMZ5KR1DdR8cBRkgpixWZlo8hDLTOxhLnesiu467m2TfuECKZy6yHdXVyt+FQrfkNZLOwEbjUpplOeD8+ngCOae/FbSadfuG8fiuheMvyuCWf/mhDL/+6R5GP/rFB6oYeJp4oepBvWzlgvTsfUujYdAXE=
